name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: 'Setup workspace'
        run: |
          pnpm i
      - name: 'Run checks'
        run: |
          lefthook run pre-commit --all-files

